# Generated by Django 2.2 on 2019-05-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(blank=True, max_length=300)),
                ('user_code', models.CharField(max_length=40, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('is_developer', models.BooleanField(default=False)),
            ],
        ),
    ]
