# Generated by Django 2.2 on 2019-05-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('animals_server', '0002_auto_20190530_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_detect', models.DateTimeField(auto_now_add=True)),
                ('health_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('health_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('happiness_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('happiness_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('thirst_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('thirst_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('hunger_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('hunger_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('strenght_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('strenght_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('stamina_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('stamina_max', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('xp_level', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_server.User')),
            ],
        ),
        migrations.CreateModel(
            name='AppRetention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.BooleanField(default=True)),
                ('timestamp_detect', models.DateTimeField(auto_now_add=True)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_server.Stats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_server.User')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_identifier', models.CharField(max_length=200)),
                ('timestamp_detect', models.DateTimeField(auto_now_add=True)),
                ('stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_server.Stats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_server.User')),
            ],
        ),
    ]
