# Generated by Django 2.2 on 2019-05-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('animals_server', '0003_action_appretention_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_country',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='user_ipinfo_all',
            field=models.TextField(blank=True),
        ),
    ]
