# Generated by Django 2.2.1 on 2019-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_server', '0004_auto_20190531_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ip',
            field=models.CharField(max_length=200),
        ),
    ]
