# Generated by Django 2.2.1 on 2019-06-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_server', '0006_stats_points_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_ip',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
